### ISSUE TITLE
static vars

### ISSUE THREAD

**Issue by Reversive** [jbro129/PG3D-Hook#2]
Hey man, nice release, how did you go about getting, for example, the weapon manager statically? Did you just traverse/brute-force lib2cpp in a loop (lib2cpp + offset) reading the static var class name until you found WeaponManager ?

**Comment by jbro129** [comment]
I cross-referenced the obfuscated functions with an old unobfuscated one. For WeaponManager I found a static instance or a method where it's used in the dump and went to an xref where its used inside of IDA and got the static offset.
